apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: canhaul.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: can-haul-api-service
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: can-haul-dashboard-service
                port:
                  number: 80