apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 80  # Service port (accessible inside cluster)
      targetPort: 80  # Pod's container port