apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-example
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: canhaul.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: can-haul-dashboard-frontend
                port:
                  number: 80