apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          proxy_pass http://can-haul-app-service:9000;  # Points to the API Service
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
    
        location /api {
          proxy_pass http://can-haul-api-service:3000;  # Points to the API Service
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }