apiVersion: apps/v1
kind: Deployment
metadata:
  name: can-haul-dashboard-frontend
spec:
  replicas: 3  # Adjust as needed
  selector:
    matchLabels:
      app: can-haul-dashboard-frontend
  template:
    metadata:
      labels:
        app: can-haul-dashboard-frontend
    spec:
      containers:
        - name: dashboard
          image: registry.digitalocean.com/can-haul-io-registry/canhaul/app:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config

---

apiVersion: v1
kind: Service
metadata:
  name: can-haul-dashboard-service
spec:
  selector:
    app: can-haul-dashboard-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP  # Internal access only