apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
     upstream chas {
        server can-haul-api-service:3000;
    }
      server {
        listen 80;
        location /api {
          proxy_pass http://chas;  # Points to the API Service
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }